# Generated by Django 5.1.1 on 2024-09-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='forum.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
            ],
        ),
    ]
